const GET_BREEDS = "GET_BREEDS";
const PUT_BREED = "PUT_BREED";
const GET_BREEDS_FAVOURITES = "GET_BREEDS_FAVOURITES";
const PUT_BREEDS_FAVOURITES = "PUT_BREEDS_FAVOURITES";  
const DELETE_BREEDS_FAVOURITES = "DELETE_BREEDS_FAVOURITES";
const GET_DETAIL_BREED = "GET_DETAIL_BREED";

module.exports = {
    GET_BREEDS,
    PUT_BREED,
    GET_BREEDS_FAVOURITES,
    PUT_BREEDS_FAVOURITES,   
    DELETE_BREEDS_FAVOURITES,
    GET_DETAIL_BREED
}
