const GET_BREEDS = "GET_BREEDS";
const GET_BREEDS_FAVOURITES = "GET_BREEDS_FAVOURITES";
const POST_BREEDS_FAVOURITES = "PUT_BREEDS_FAVOURITES";  
const DELETE_BREEDS_FAVOURITES = "DELETE_BREEDS_FAVOURITES";
const GET_DETAIL_BREED = "GET_DETAIL_BREED";
const GET_BREEDS_FILTER = "GET_BREEDS_FILTER";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const FILTER_CREATED = "FILTER_CREATED" ; 
const FILTER_EXISTING =  "FILTER_EXISTING";
const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
const FILTER_BY_AZ = "FILTER_BY_AZ";
const FILTER_WEIGHT = "FILTER_WEIGHT";
const GET_BREEDS_FOR_FILTER = "GET_BREEDS_FOR_FILTER";

module.exports = {
    GET_BREEDS,
    GET_BREEDS_FILTER,
    GET_BREEDS_FAVOURITES,
    POST_BREEDS_FAVOURITES,   
    DELETE_BREEDS_FAVOURITES,
    GET_DETAIL_BREED,
    GET_TEMPERAMENTS,
    FILTER_CREATED,
    FILTER_EXISTING,
    FILTER_BY_TEMPERAMENT,
    FILTER_BY_AZ,
    FILTER_WEIGHT,
    GET_BREEDS_FOR_FILTER,

}
